#  pylint: disable=duplicate-code
from cli_wrapper.cli_wrapper import CLIWrapper

wrapper_config = {
    "path": "cilium",
    "env": None,
    "commands": {
        "bgp": {"cli_command": "bgp", "default_flags": {"o": "json"}, "args": {}, "parse": "json"},
        "bgp_peers": {
            "cli_command": ["bgp", "peers"],
            "default_flags": {"o": "json"},
            "args": {
                "context": {"literal_name": "context", "default": None, "validator": "is_str"},
                "helm-release-name": {"literal_name": "helm-release-name", "default": None, "validator": "is_str"},
                "help": {"literal_name": "help", "default": None, "validator": "is_bool"},
                "namespace": {"literal_name": "namespace", "default": None, "validator": "is_str"},
                'help"': {"literal_name": 'help"', "default": None, "validator": "is_bool"},
            },
            "parse": "json",
        },
        "bgp_routes": {
            "cli_command": ["bgp", "routes"],
            "default_flags": {"o": "json"},
            "args": {
                "context": {"literal_name": "context", "default": None, "validator": "is_str"},
                "helm-release-name": {"literal_name": "helm-release-name", "default": None, "validator": "is_str"},
                "help": {"literal_name": "help", "default": None, "validator": "is_bool"},
                "namespace": {"literal_name": "namespace", "default": None, "validator": "is_str"},
                'help"': {"literal_name": 'help"', "default": None, "validator": "is_bool"},
            },
            "parse": "json",
        },
        "clustermesh": {"cli_command": "clustermesh", "default_flags": {"o": "json"}, "args": {}, "parse": "json"},
        "clustermesh_connect": {
            "cli_command": ["clustermesh", "connect"],
            "default_flags": {"o": "json"},
            "args": {
                "context": {"literal_name": "context", "default": None, "validator": "is_str"},
                "helm-release-name": {"literal_name": "helm-release-name", "default": None, "validator": "is_str"},
                "help": {"literal_name": "help", "default": None, "validator": "is_bool"},
                "namespace": {"literal_name": "namespace", "default": None, "validator": "is_str"},
                'help"': {"literal_name": 'help"', "default": None, "validator": "is_bool"},
            },
            "parse": "json",
        },
        "clustermesh_disable": {
            "cli_command": ["clustermesh", "disable"],
            "default_flags": {"o": "json"},
            "args": {
                "context": {"literal_name": "context", "default": None, "validator": "is_str"},
                "helm-release-name": {"literal_name": "helm-release-name", "default": None, "validator": "is_str"},
                "help": {"literal_name": "help", "default": None, "validator": "is_bool"},
                "namespace": {"literal_name": "namespace", "default": None, "validator": "is_str"},
                'help"': {"literal_name": 'help"', "default": None, "validator": "is_bool"},
            },
            "parse": "json",
        },
        "clustermesh_disconnect": {
            "cli_command": ["clustermesh", "disconnect"],
            "default_flags": {"o": "json"},
            "args": {
                "context": {"literal_name": "context", "default": None, "validator": "is_str"},
                "helm-release-name": {"literal_name": "helm-release-name", "default": None, "validator": "is_str"},
                "help": {"literal_name": "help", "default": None, "validator": "is_bool"},
                "namespace": {"literal_name": "namespace", "default": None, "validator": "is_str"},
                'help"': {"literal_name": 'help"', "default": None, "validator": "is_bool"},
            },
            "parse": "json",
        },
        "clustermesh_enable": {
            "cli_command": ["clustermesh", "enable"],
            "default_flags": {"o": "json"},
            "args": {
                "context": {"literal_name": "context", "default": None, "validator": "is_str"},
                "helm-release-name": {"literal_name": "helm-release-name", "default": None, "validator": "is_str"},
                "help": {"literal_name": "help", "default": None, "validator": "is_bool"},
                "namespace": {"literal_name": "namespace", "default": None, "validator": "is_str"},
                'help"': {"literal_name": 'help"', "default": None, "validator": "is_bool"},
            },
            "parse": "json",
        },
        "clustermesh_external_workload": {
            "cli_command": ["clustermesh", "external-workload"],
            "default_flags": {"o": "json"},
            "args": {
                "context": {"literal_name": "context", "default": None, "validator": "is_str"},
                "helm-release-name": {"literal_name": "helm-release-name", "default": None, "validator": "is_str"},
                "help": {"literal_name": "help", "default": None, "validator": "is_bool"},
                "namespace": {"literal_name": "namespace", "default": None, "validator": "is_str"},
                'help"': {"literal_name": 'help"', "default": None, "validator": "is_bool"},
            },
            "parse": "json",
        },
        "clustermesh_status": {
            "cli_command": ["clustermesh", "status"],
            "default_flags": {"o": "json"},
            "args": {
                "context": {"literal_name": "context", "default": None, "validator": "is_str"},
                "helm-release-name": {"literal_name": "helm-release-name", "default": None, "validator": "is_str"},
                "help": {"literal_name": "help", "default": None, "validator": "is_bool"},
                "namespace": {"literal_name": "namespace", "default": None, "validator": "is_str"},
                'help"': {"literal_name": 'help"', "default": None, "validator": "is_bool"},
            },
            "parse": "json",
        },
        "completion": {"cli_command": "completion", "default_flags": {"o": "json"}, "args": {}, "parse": "json"},
        "completion_bash": {
            "cli_command": ["completion", "bash"],
            "default_flags": {"o": "json"},
            "args": {
                "context": {"literal_name": "context", "default": None, "validator": "is_str"},
                "helm-release-name": {"literal_name": "helm-release-name", "default": None, "validator": "is_str"},
                "help": {"literal_name": "help", "default": None, "validator": "is_bool"},
                "namespace": {"literal_name": "namespace", "default": None, "validator": "is_str"},
                'help"': {"literal_name": 'help"', "default": None, "validator": "is_bool"},
            },
            "parse": "json",
        },
        "completion_fish": {
            "cli_command": ["completion", "fish"],
            "default_flags": {"o": "json"},
            "args": {
                "context": {"literal_name": "context", "default": None, "validator": "is_str"},
                "helm-release-name": {"literal_name": "helm-release-name", "default": None, "validator": "is_str"},
                "help": {"literal_name": "help", "default": None, "validator": "is_bool"},
                "namespace": {"literal_name": "namespace", "default": None, "validator": "is_str"},
                'help"': {"literal_name": 'help"', "default": None, "validator": "is_bool"},
            },
            "parse": "json",
        },
        "completion_powershell": {
            "cli_command": ["completion", "powershell"],
            "default_flags": {"o": "json"},
            "args": {
                "context": {"literal_name": "context", "default": None, "validator": "is_str"},
                "helm-release-name": {"literal_name": "helm-release-name", "default": None, "validator": "is_str"},
                "help": {"literal_name": "help", "default": None, "validator": "is_bool"},
                "namespace": {"literal_name": "namespace", "default": None, "validator": "is_str"},
                'help"': {"literal_name": 'help"', "default": None, "validator": "is_bool"},
            },
            "parse": "json",
        },
        "completion_zsh": {
            "cli_command": ["completion", "zsh"],
            "default_flags": {"o": "json"},
            "args": {
                "context": {"literal_name": "context", "default": None, "validator": "is_str"},
                "helm-release-name": {"literal_name": "helm-release-name", "default": None, "validator": "is_str"},
                "help": {"literal_name": "help", "default": None, "validator": "is_bool"},
                "namespace": {"literal_name": "namespace", "default": None, "validator": "is_str"},
                'help"': {"literal_name": 'help"', "default": None, "validator": "is_bool"},
            },
            "parse": "json",
        },
        "config": {"cli_command": "config", "default_flags": {"o": "json"}, "args": {}, "parse": "json"},
        "config_delete": {
            "cli_command": ["config", "delete"],
            "default_flags": {"o": "json"},
            "args": {
                "context": {"literal_name": "context", "default": None, "validator": "is_str"},
                "helm-release-name": {"literal_name": "helm-release-name", "default": None, "validator": "is_str"},
                "help": {"literal_name": "help", "default": None, "validator": "is_bool"},
                "namespace": {"literal_name": "namespace", "default": None, "validator": "is_str"},
                'help"': {"literal_name": 'help"', "default": None, "validator": "is_bool"},
            },
            "parse": "json",
        },
        "config_set": {
            "cli_command": ["config", "set"],
            "default_flags": {"o": "json"},
            "args": {
                "context": {"literal_name": "context", "default": None, "validator": "is_str"},
                "helm-release-name": {"literal_name": "helm-release-name", "default": None, "validator": "is_str"},
                "help": {"literal_name": "help", "default": None, "validator": "is_bool"},
                "namespace": {"literal_name": "namespace", "default": None, "validator": "is_str"},
                'help"': {"literal_name": 'help"', "default": None, "validator": "is_bool"},
            },
            "parse": "json",
        },
        "config_view": {
            "cli_command": ["config", "view"],
            "default_flags": {"o": "json"},
            "args": {
                "context": {"literal_name": "context", "default": None, "validator": "is_str"},
                "helm-release-name": {"literal_name": "helm-release-name", "default": None, "validator": "is_str"},
                "help": {"literal_name": "help", "default": None, "validator": "is_bool"},
                "namespace": {"literal_name": "namespace", "default": None, "validator": "is_str"},
                'help"': {"literal_name": 'help"', "default": None, "validator": "is_bool"},
            },
            "parse": "json",
        },
        "connectivity": {"cli_command": "connectivity", "default_flags": {"o": "json"}, "args": {}, "parse": "json"},
        "connectivity_perf": {
            "cli_command": ["connectivity", "perf"],
            "default_flags": {"o": "json"},
            "args": {
                "context": {"literal_name": "context", "default": None, "validator": "is_str"},
                "helm-release-name": {"literal_name": "helm-release-name", "default": None, "validator": "is_str"},
                "help": {"literal_name": "help", "default": None, "validator": "is_bool"},
                "namespace": {"literal_name": "namespace", "default": None, "validator": "is_str"},
                'help"': {"literal_name": 'help"', "default": None, "validator": "is_bool"},
            },
            "parse": "json",
        },
        "connectivity_test": {
            "cli_command": ["connectivity", "test"],
            "default_flags": {"o": "json"},
            "args": {
                "context": {"literal_name": "context", "default": None, "validator": "is_str"},
                "helm-release-name": {"literal_name": "helm-release-name", "default": None, "validator": "is_str"},
                "help": {"literal_name": "help", "default": None, "validator": "is_bool"},
                "namespace": {"literal_name": "namespace", "default": None, "validator": "is_str"},
                'help"': {"literal_name": 'help"', "default": None, "validator": "is_bool"},
            },
            "parse": "json",
        },
        "context": {"cli_command": "context", "default_flags": {"o": "json"}, "args": {}, "parse": "json"},
        "encryption": {"cli_command": "encryption", "default_flags": {"o": "json"}, "args": {}, "parse": "json"},
        "encryption_key_status": {
            "cli_command": ["encryption", "key-status"],
            "default_flags": {"o": "json"},
            "args": {
                "context": {"literal_name": "context", "default": None, "validator": "is_str"},
                "helm-release-name": {"literal_name": "helm-release-name", "default": None, "validator": "is_str"},
                "help": {"literal_name": "help", "default": None, "validator": "is_bool"},
                "namespace": {"literal_name": "namespace", "default": None, "validator": "is_str"},
                'help"': {"literal_name": 'help"', "default": None, "validator": "is_bool"},
            },
            "parse": "json",
        },
        "encryption_rotate_key": {
            "cli_command": ["encryption", "rotate-key"],
            "default_flags": {"o": "json"},
            "args": {
                "context": {"literal_name": "context", "default": None, "validator": "is_str"},
                "helm-release-name": {"literal_name": "helm-release-name", "default": None, "validator": "is_str"},
                "help": {"literal_name": "help", "default": None, "validator": "is_bool"},
                "namespace": {"literal_name": "namespace", "default": None, "validator": "is_str"},
                'help"': {"literal_name": 'help"', "default": None, "validator": "is_bool"},
            },
            "parse": "json",
        },
        "encryption_status": {
            "cli_command": ["encryption", "status"],
            "default_flags": {"o": "json"},
            "args": {
                "context": {"literal_name": "context", "default": None, "validator": "is_str"},
                "helm-release-name": {"literal_name": "helm-release-name", "default": None, "validator": "is_str"},
                "help": {"literal_name": "help", "default": None, "validator": "is_bool"},
                "namespace": {"literal_name": "namespace", "default": None, "validator": "is_str"},
                'help"': {"literal_name": 'help"', "default": None, "validator": "is_bool"},
            },
            "parse": "json",
        },
        "help": {"cli_command": "help", "default_flags": {"o": "json"}, "args": {}, "parse": "json"},
        "hubble": {"cli_command": "hubble", "default_flags": {"o": "json"}, "args": {}, "parse": "json"},
        "hubble_disable": {
            "cli_command": ["hubble", "disable"],
            "default_flags": {"o": "json"},
            "args": {
                "context": {"literal_name": "context", "default": None, "validator": "is_str"},
                "helm-release-name": {"literal_name": "helm-release-name", "default": None, "validator": "is_str"},
                "help": {"literal_name": "help", "default": None, "validator": "is_bool"},
                "namespace": {"literal_name": "namespace", "default": None, "validator": "is_str"},
                'help"': {"literal_name": 'help"', "default": None, "validator": "is_bool"},
            },
            "parse": "json",
        },
        "hubble_enable": {
            "cli_command": ["hubble", "enable"],
            "default_flags": {"o": "json"},
            "args": {
                "context": {"literal_name": "context", "default": None, "validator": "is_str"},
                "helm-release-name": {"literal_name": "helm-release-name", "default": None, "validator": "is_str"},
                "help": {"literal_name": "help", "default": None, "validator": "is_bool"},
                "namespace": {"literal_name": "namespace", "default": None, "validator": "is_str"},
                'help"': {"literal_name": 'help"', "default": None, "validator": "is_bool"},
            },
            "parse": "json",
        },
        "hubble_port_forward": {
            "cli_command": ["hubble", "port-forward"],
            "default_flags": {"o": "json"},
            "args": {
                "context": {"literal_name": "context", "default": None, "validator": "is_str"},
                "helm-release-name": {"literal_name": "helm-release-name", "default": None, "validator": "is_str"},
                "help": {"literal_name": "help", "default": None, "validator": "is_bool"},
                "namespace": {"literal_name": "namespace", "default": None, "validator": "is_str"},
                'help"': {"literal_name": 'help"', "default": None, "validator": "is_bool"},
            },
            "parse": "json",
        },
        "hubble_ui": {
            "cli_command": ["hubble", "ui"],
            "default_flags": {"o": "json"},
            "args": {
                "context": {"literal_name": "context", "default": None, "validator": "is_str"},
                "helm-release-name": {"literal_name": "helm-release-name", "default": None, "validator": "is_str"},
                "help": {"literal_name": "help", "default": None, "validator": "is_bool"},
                "namespace": {"literal_name": "namespace", "default": None, "validator": "is_str"},
                'help"': {"literal_name": 'help"', "default": None, "validator": "is_bool"},
            },
            "parse": "json",
        },
        "install": {"cli_command": "install", "default_flags": {"o": "json"}, "args": {}, "parse": "json"},
        "status": {"cli_command": "status", "default_flags": {"o": "json"}, "args": {}, "parse": "json"},
        "sysdump": {"cli_command": "sysdump", "default_flags": {"o": "json"}, "args": {}, "parse": "json"},
        "uninstall": {"cli_command": "uninstall", "default_flags": {"o": "json"}, "args": {}, "parse": "json"},
        "upgrade": {"cli_command": "upgrade", "default_flags": {"o": "json"}, "args": {}, "parse": "json"},
        "version": {"cli_command": "version", "args": {}},
    },
    "trusting": True,
    "async_": False,
    "default_transformer": "snake2kebab",
    "short_prefix": "-",
    "long_prefix": "--",
    "arg_separator": " ",
}


def get_cilium():
    return CLIWrapper.from_dict(wrapper_config)
