---
name: static-analysis
on: push
jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    container: python:3.12
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 2
      - name: install prerequisites
        run: |
          pip install .[check] .[test] black pylint
      - name: run black
        run: |
          black --check --diff .
      - name: run pylint
        run: |
          pylint --fail-under 10 src
          pylint --fail-under 10 --disable=protected-access tests
      - name: run tests
        run: |
          pytest . --cov-report lcov
      - uses: qltysh/qlty-action/coverage@main
        with:
          token: ${{secrets.QLTY_COVERAGE_TOKEN}}
          files: coverage.lcov
