---
name: static-analysis
on: push
jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    container: python:3.12
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 2
      - name: install prerequisites
        run: |
          pip install .[check] .[test] black pylint
      - name: run black
        run: |
          black --check --diff .
      - name: run pylint
        run: |
          pylint --fail-under 10 src
          pylint --fail-under 10 --disable=protected-access tests
      - name: run tests
        run: |
          pytest -n 4 -Walways --cov=cli_wrapper --cov-branch --cov-report xml .
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}