name: Publish to PyPI
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  pypi:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/cli_wrapper
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: build a wheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          python -m build -w
      - name: publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1